### PR TITLE
Fix issue calibrate.cfg

### PR DESCRIPTION
**Pull request by fbeauKmi**
Hi, I made some small adjustment in calibrate.cfg to avoid enter END_PRINT if test is not statified and  change to enlarge Error perimeter. 
Bed_mesh.cfg (no need to have mesh_pps in config addind default value in the test

### CODE REVIEW

**Comment by fbeauKmi** [comment]
Sorry, files are not there ... Strange behavior in VisualStudio.  I'll manage later

**Comment by fbeauKmi** [comment]
Here it is !

**Comment by Frix-x** [comment]
Thank you for this PR !
I'll review it when the #11 will be merged in the next few hours/days :)

**Review by Frix-x — APPROVED** [review]
Thank you for this !
I'll merge it :)

**Pull request merged**
